"""Proposal publisher — creates GitHub Issues from structured improvement proposals."""

import os

from github import Github, GithubException
from models import ImprovementProposal


def publish(proposals: list[ImprovementProposal]) -> list[str]:
    """Create GitHub Issues from proposals. Returns list of issue URLs."""
    token = os.environ.get("GITHUB_TOKEN")
    repo_name = os.environ.get("GITHUB_REPO")

    if not token or not repo_name:
        print("  ⚠️  GITHUB_TOKEN or GITHUB_REPO not set — printing proposals instead.")
        for p in proposals:
            print(f"  📋 {p.title} (confidence: {p.confidence:.0%})")
        return []

    gh = Github(token)
    repo = gh.get_repo(repo_name)
    urls = []

    for proposal in proposals:
        body = _format_issue_body(proposal)

        try:
            issue = repo.create_issue(
                title=f"🤖 {proposal.title}",
                body=body,
                labels=_ensure_labels(repo, proposal),
            )
            urls.append(issue.html_url)
        except GithubException as e:
            print(f"  ⚠️  Failed to create issue for '{proposal.title}': {e}")

    return urls


def _format_issue_body(proposal: ImprovementProposal) -> str:
    evidence_lines = "\n".join(
        f"- **{e.source}**: {e.detail}" for e in proposal.evidence
    )

    return (
        f"## Platform Improvement Proposal\n\n"
        f"**Golden path step:** {proposal.golden_path_step}\n\n"
        f"### Problem\n{proposal.problem}\n\n"
        f"### Recommendation\n{proposal.recommendation}\n\n"
        f"**Confidence:** {proposal.confidence:.0%}\n\n"
        f"**Estimated impact:** {proposal.estimated_impact}\n\n"
        f"### Evidence\n{evidence_lines}\n\n"
        f"---\n"
        f"*Auto-generated by the platform feedback agent. "
        f"Review and approve/reject. Agent learns from your decision.*"
    )


def _ensure_labels(repo, proposal: ImprovementProposal) -> list[str]:
    label_names = ["agent-proposal", f"step:{proposal.golden_path_step}"]
    for name in label_names:
        try:
            repo.get_label(name)
        except GithubException:
            repo.create_label(name, color="0075ca")
    return label_names
